// Day9/Assignments/Assignment1/Source/vue-app/src/App.vue
<script>
  import { useVuelidate } from "@vuelidate/core";
  import { required, helpers, minLength } from "@vuelidate/validators";
  import Errors from "./components/Errors.vue";

    export default{
    data() {
        return {
            v$: useVuelidate(),
            stdList:[],
            form: {
                student: {
                    fname: "",
                    mname: "",
                    lname: "",
                    dob: "",
                    birthPlace: "",
                    firstLang: "",
                    city: "",
                    state: "",
                    pin: ""
                },
                father: {
                    fname: "",
                    mname: "",
                    lname: "",
                    email: "",
                    education: "",
                    profession: "",
                    designation: "",
                    mobile: ""
                },
                mother: {
                    fname: "",
                    mname: "",
                    lname: "",
                    email: "",
                    education: "",
                    profession: "",
                    designation: "",
                    mobile: ""
                }
            }
        };
    },
    validations() {
        return {
            form: {
                student: {
                    fname: { required: helpers.withMessage('First name is required!', required) },
                    mname: { required: helpers.withMessage('Middle name is required!', required) },
                    lname: { required: helpers.withMessage('Last name is required!', required) },
                    dob: { required: helpers.withMessage('Date of Birth is required!', required) }
                },
                father: {
                    fname: { required: helpers.withMessage('First name is required!', required) },
                    mname: { required: helpers.withMessage('Middle name is required!', required) },
                    lname: { required: helpers.withMessage('Last name is required!', required) },
                    mobile: { required: helpers.withMessage('Mobile Number is required!', required) }
                },
                mother: {
                    fname: { required: helpers.withMessage('First name is required!', required) },
                    mname: { required: helpers.withMessage('Middle name is required!', required) },
                    lname: { required: helpers.withMessage('Last name is required!', required) },
                    mobile: { required: helpers.withMessage('Mobile is required!', required) }
                }
            }
        };
    },
    components: { Errors },
    methods:{
      submit(e){
        e.preventDefault()
        if(this.v$.$validate()) this.stdList.push(this.form)
        return;
      }
    }
}
</script>

<template>
  <div>
  <div class="container">
    <form  class="d-flex justify-content-between" @submit="submit">
        <div  id="student">
          <h3>Student Details :-</h3>
            <div>
                <div class="form-group my-3">
                  <label for="firstName">First Name:-</label>
                  <input formControlName="firstName" v-model="form.student.fname" @blur="v$.form.student.fname.$touch" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname"> 
                  <Errors :errors="v$.form.student.fname.$errors"></Errors>
                </div>
                <div class="form-group my-3">
                  <label for="middleName">Middle Name:-</label>
                  <input formControlName="middleName" v-model="form.student.mname" @blur="v$.form.student.mname.$touch" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">
                  <Errors :errors="v$.form.student.mname.$errors"></Errors>
                </div>
                
                <div class="form-group my-3">
                  <label for="lastName">Last Name:-</label>
                  <input formControlName="lastName" v-model="form.student.lname" @blur="v$.form.student.lname.$touch" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
                  <Errors :errors="v$.form.student.lname.$errors"></Errors>
                </div>                

              </div>

            <div>
              <div class="form-group my-3">
                <label for="dob">DOB:-</label>
                <input formControlName="dob" v-model="form.student.dob" @blur="v$.form.student.dob.$touch" class="form-control" type="date" id="dob" name="dob">                
                <Errors :errors="v$.form.student.dob.$errors"></Errors>
              </div>

              <div class="form-group my-3">
                <label for="birthPlace">Birth Place:-</label>
                <input formControlName="birthPlace" v-model="form.student.birthPlace" class="form-control" type="text" id="birthPlace" name="birthPlace" placeholder="Enter Birth Place">  
              </div>

              <div class="form-group my-3">
                <label for="firstLang">First Language:-</label>
                <input formControlName="firstLang" v-model="form.student.firstLang" class="form-control" type="text" id="firstLang" name="firstLang" placeholder="Enter First Language">
              </div>
            </div>

            <div >
              <div class="form-group my-3">
                <label for="city">City:-</label>
                <input formControlName="city" v-model="form.student.city" class="form-control" type="text" id="city" name="city" placeholder="Enter Your City">  
              </div>

              <div class="form-group my-3">
                <label for="State">State:-</label>
                <input formControlName="state" v-model="form.student.state" class="form-control" type="text" id="State" name="State" placeholder="Enter Your State">
              </div>              

              <div class="form-group my-3">
                <label for="pin">Enter Pin Code:-</label>
                <input formControlName="pinCode" v-model="form.student.pin" class="form-control" type="text" id="pin" name="pin" placeholder="Pincode">
              </div>

            </div>
        </div>
        <div id="father" >
          <h3>Father's Details :-</h3>
          <div >
              <div class="form-group my-3">
                <label for="firstName">First Name:-</label>
                <input formControlName="firstName" v-model="form.father.fname" @blur="v$.form.father.fname.$touch" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">
                <Errors :errors="v$.form.father.fname.$errors"></Errors>
              </div>
              <div class="form-group my-3">
                <label for="middleName">Middle Name:-</label>
                <input formControlName="middleName" v-model="form.father.mname" @blur="v$.form.father.mname.$touch" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">  
                <Errors :errors="v$.form.father.mname.$errors"></Errors>
              </div>
              <div class="form-group my-3">
                <label for="lastName">Last Name:-</label>
                <input formControlName="lastName" v-model="form.father.lname" @blur="v$.form.father.lname.$touch" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
                <Errors :errors="v$.form.father.lname.$errors"></Errors>
              </div>
          </div>

          <div class="form-group my-3">
            <label for="email">Email :-</label>
            <input formControlName="email" v-model="form.father.email" class="form-control" type="email" id="email" name="email" placeholder="Enter Email">            
          </div>

          <div class="form-group my-3">
            <label for="education">Education Qualification:-</label>
            <input formControlName="education" v-model="form.father.education" class="form-control" type="text" id="education" name="education" placeholder="Enter Education">
          </div>
          
          <div class="form-group my-3">
            <label for="profession">Profession:-</label>
            <input formControlName="profession" v-model="form.father.profession" class="form-control" type="text" id="profession" name="profession" placeholder="Enter Profession">  
          </div>

          <div class="form-group my-3">
            <label for="designation">Designation:-</label>
            <input formControlName="desgnation" v-model="form.father.designation" class="form-control" type="text" id="designation" name="designation" placeholder="Enter Designation">
          </div>
          
          <div class="form-group my-3">
            <label for="moblie">Moblie Number:-</label>
            <input formControlName="mobile" v-model="form.father.mobile" @blur="v$.form.father.mobile.$touch" class="form-control" type="text" id="moblie" name="moblie" placeholder="Enter Mobile Number">
            <Errors :errors="v$.form.father.mobile.$errors"></Errors>
          </div>

        </div>  
        <div  id="mother">
          <h3>Mother's Details :-</h3>
          <div>
            <div class="form-group my-3">
              <label for="firstName">First Name:-</label>
              <input formControlName="firstName" v-model="form.mother.fname" @blur="v$.form.mother.fname.$touch" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">  
              <Errors :errors="v$.form.mother.fname.$errors"></Errors>
            </div>

            <div class="form-group my-3">
              <label for="middleName">Middle Name:-</label>
              <input formControlName="middleName" v-model="form.mother.mname" @blur="v$.form.mother.mname.$touch" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">  
              <Errors :errors="v$.form.mother.mname.$errors"></Errors>
            </div>

            <div class="form-group my-3">
              <label for="lastName">Last Name:-</label>
              <input formControlName="lastName" v-model="form.mother.lname" @blur="v$.form.mother.lname.$touch" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
              <Errors :errors="v$.form.mother.lname.$errors"></Errors>
            </div>
         </div>

          <div class="form-group my-3">
            <label for="email">Email :-</label>
            <input formControlName="email" v-model="form.mother.email" class="form-control" type="email" id="email" name="email" placeholder="Enter Email">
          </div>

          <div class="form-group my-3">
            <label for="education">Education Qualification:-</label>
            <input formControlName="education" v-model="form.mother.education" class="form-control" type="text" id="education" name="education" placeholder="Enter Education">
          </div>

          <div class="form-group my-3">
            <label for="profession">Profession:-</label>
            <input formControlName="profession" v-model="form.mother.profession" class="form-control" type="text" id="profession" name="profession" placeholder="Enter Profession">
          </div>

          <div class="form-group my-3">
            <label for="designation">Designation:-</label>
            <input formControlName="desgnation" v-model="form.mother.designation" class="form-control" type="text" id="designation" name="designation" placeholder="Enter Designation">
          </div>

          <div class="form-group my-3">
            <label for="moblie">Moblie Number:-</label>
            <input formControlName="mobile" v-model="form.mother.mobile" @blur="v$.form.mother.mobile.$touch" class="form-control" type="text" id="moblie" name="moblie" placeholder="Enter Mobile Number">
            <Errors :errors="v$.form.mother.mobile.$errors"></Errors>
          </div>        
        </div>

        <div>
          <h4>Emergency contect :-</h4>
          <div formArrayName="emeList">
            <div  class="form-group my-3">
              <div >
                <div>
                  <label for="designation">Name:-</label>
                  <input formControlName="name" class="form-control" type="text" id="name" name="name" placeholder="Enter Name">                      
                </div>
                <div>
                  <label for="designation">Number:-</label>
                  <input formControlName="number" class="form-control" type="text" id="number" name="number" placeholder="Enter Number">  
                </div>
              </div>
            </div>  
          </div>
          <div>
            <button type="button" >Add person</button>
            <button type="button">Remove person</button>

          </div>
          <button class="btn btn-success" type="submit">Submit</button>
          </div>
      </form>
  </div>
</div>
<!-- {{form.value | json}} -->

{{Object.keys(v$.form.father)}}
</template>

<style>
</style>

// Day8/Assignments/Assignment1/Source/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormArray, FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
    emeList=new FormArray([
      new FormGroup({
        name:new FormControl('',Validators.required),
        number:new FormControl('',Validators.required)  
      })
  ])
  form=new FormGroup({
      student:new FormGroup({
        Name:new FormGroup({
          firstName:new FormControl('',[Validators.required,Validators.minLength(3)]),
          middleName:new FormControl('',[Validators.required,Validators.minLength(3)]),
          lastName:new FormControl('', [Validators.required,Validators.minLength(3)])
        }),
        personalDetails:new FormGroup({
          dob:new FormControl('',Validators.required),
          birthPlace:new FormControl('',Validators.required),
          firstLang:new FormControl('',Validators.required)
        }),
        adress:new FormGroup({
          city:new FormControl('',Validators.required),
          state:new FormControl('',Validators.required),
          pinCode:new FormControl('',Validators.required)
        }),
      }),
      father:new FormGroup({
        Name:new FormGroup({
          firstName:new FormControl('',Validators.required),
          middleName:new FormControl('',Validators.required),
          lastName:new FormControl('',Validators.required)
        }),
        email:new FormControl('',Validators.required),
        education:new FormControl('',Validators.required),
        desgnation:new FormControl('',Validators.required),
        profession:new FormControl('',Validators.required),
        mobile:new FormControl('',Validators.required)
      }),
      mother:new FormGroup({
        Name:new FormGroup({
          firstName:new FormControl('',Validators.required),
          middleName:new FormControl('',Validators.required),
          lastName:new FormControl('',Validators.required)
        }),
        email:new FormControl('',Validators.required),
        education:new FormControl('',Validators.required),
        desgnation:new FormControl('',Validators.required),
        profession:new FormControl('',Validators.required),
        mobile:new FormControl('',Validators.required)
      }),
      EmergencyList:new FormGroup({
        emeList:this.emeList
      })
  })
  title = 'angular-app';


  addEme(){
    this.emeList.push(
      new FormGroup({
        name:new FormControl('',Validators.required),
        number:new FormControl('',Validators.required)  
      })
    )
  }

  removeEme(){
    this.emeList.removeAt(this.emeList.length-1)
  }

  get studFname(){
    return this.form.controls.student.controls.Name.controls.firstName;
  }

  get studMname(){
    return this.form.controls.student.controls.Name.controls.middleName;
  }

  get studLname(){
    return this.form.controls.student.controls.Name.controls.lastName;
  }

  get studDate(){
    return this.form.controls.student.controls.personalDetails.controls.dob;
  }

  get studBirthPlace(){
    return this.form.controls.student.controls.personalDetails.controls.birthPlace;
  }

  get studFirstLang(){
    return this.form.controls.student.controls.personalDetails.controls.firstLang;
  }
  get studCity(){
    return this.form.controls.student.controls.adress.controls.city;
  }
  get studState(){
    return this.form.controls.student.controls.adress.controls.state;
  }
  get studPincode(){
    return this.form.controls.student.controls.adress.controls.pinCode;
  }
  get fatherFname(){
    return this.form.controls.father.controls.Name.controls.firstName;
  }
  get fatherMname(){
    return this.form.controls.father.controls.Name.controls.middleName;
  }
  get fatherLname(){
    return this.form.controls.father.controls.Name.controls.lastName;
  }
  get fatherEmail(){
    return this.form.controls.father.controls.email;
  }
  get fatherEducation(){
    return this.form.controls.father.controls.education;
  }
  get fatherProfession(){
    return this.form.controls.father.controls.profession;
  }
  get fatherDesgnation(){
    return this.form.controls.father.controls.desgnation;
  }
  get fatherMobile(){
    return this.form.controls.father.controls.mobile;
  }


  get motherFname(){
    return this.form.controls.mother.controls.Name.controls.firstName;
  }
  get motherMname(){
    return this.form.controls.mother.controls.Name.controls.middleName;
  }
  get motherLname(){
    return this.form.controls.mother.controls.Name.controls.lastName;
  }
  get motherEmail(){
    return this.form.controls.mother.controls.email;
  }
  get motherEducation(){
    return this.form.controls.mother.controls.education;
  }
  get motherProfession(){
    return this.form.controls.mother.controls.profession;
  }
  get motherDesgnation(){
    return this.form.controls.mother.controls.desgnation;
  }
  get motherMobile(){
    return this.form.controls.mother.controls.mobile;
  }


  onSubmit(){
    console.log(this.studFname.errors);
  }
}

<div>
  <div class="container">
    <form [formGroup]="form" class="d-flex justify-content-between" (ngSubmit)="onSubmit()">
        <div formGroupName="student" id="student">
          <h3>Student Details :-</h3>
            <div formGroupName = 'Name'>
                <div class="form-group my-3">
                  <label for="firstName">First Name:-</label>
                  <input formControlName="firstName" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">
                  <app-errors [field]="studFname"></app-errors>
                </div>
                <div class="form-group my-3">
                  <label for="middleName">Middle Name:-</label>
                  <input formControlName="middleName" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">
                </div>
                <app-errors [field]="studMname"></app-errors>
                <div class="form-group my-3">
                  <label for="lastName">Last Name:-</label>
                  <input formControlName="lastName" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
                </div>
                <app-errors [field]="studLname"></app-errors>
            </div>

            <div formGroupName = 'personalDetails'>
              <div class="form-group my-3">
                <label for="dob">DOB:-</label>
                <input formControlName="dob" class="form-control" type="date" id="dob" name="dob">
                <app-errors [field]="studDate"></app-errors>
              </div>
              <div class="form-group my-3">
                <label for="birthPlace">Birth Place:-</label>
                <input formControlName="birthPlace" class="form-control" type="text" id="birthPlace" name="birthPlace" placeholder="Enter Birth Place">
                <app-errors [field]="studBirthPlace"></app-errors>
              </div>
              <div class="form-group my-3">
                <label for="firstLang">First Language:-</label>
                <input formControlName="firstLang" class="form-control" type="text" id="firstLang" name="firstLang" placeholder="Enter First Language">
                <app-errors [field]="studFirstLang"></app-errors>
              </div>
            </div>

            <div formGroupName="adress">
              <div class="form-group my-3">
                <label for="city">City:-</label>
                <input formControlName="city" class="form-control" type="text" id="city" name="city" placeholder="Enter Your City">
                <app-errors [field]="studCity"></app-errors>
              </div>
              <div class="form-group my-3">
                <label for="State">State:-</label>
                <input formControlName="state" class="form-control" type="text" id="State" name="State" placeholder="Enter Your State">
                <app-errors [field]="studState"></app-errors>
              </div>              
              <div class="form-group my-3">
                <label for="pin">Enter Pin Code:-</label>
                <input formControlName="pinCode" class="form-control" type="text" id="pin" name="pin" placeholder="Pincode">
                <app-errors [field]="studPincode"></app-errors>
              </div>
            </div>
        </div>
        <div id="father" formGroupName="father">
          <h3>Father's Details :-</h3>
          <div formGroupName="Name">
              <div class="form-group my-3">
                <label for="firstName">First Name:-</label>
                <input formControlName="firstName" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">
                <app-errors [field]="fatherFname"></app-errors>
              </div>
              <div class="form-group my-3">
                <label for="middleName">Middle Name:-</label>
                <input formControlName="middleName" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">
                <app-errors [field]="fatherMname"></app-errors>
              </div>
              <div class="form-group my-3">
                <label for="lastName">Last Name:-</label>
                <input formControlName="lastName" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
                <app-errors [field]="fatherLname"></app-errors>
              </div>
          </div>
          <div class="form-group my-3">
            <label for="email">Email :-</label>
            <input formControlName="email" class="form-control" type="email" id="email" name="email" placeholder="Enter Email">
            <app-errors [field]="fatherEmail"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="education">Education Qualification:-</label>
            <input formControlName="education" class="form-control" type="text" id="education" name="education" placeholder="Enter Education">
            <app-errors [field]="fatherEducation"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="profession">Profession:-</label>
            <input formControlName="profession" class="form-control" type="text" id="profession" name="profession" placeholder="Enter Profession">
            <app-errors [field]="fatherProfession"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="designation">Designation:-</label>
            <input formControlName="desgnation" class="form-control" type="text" id="designation" name="designation" placeholder="Enter Designation">
            <app-errors [field]="fatherDesgnation"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="moblie">Moblie Number:-</label>
            <input formControlName="mobile" class="form-control" type="text" id="moblie" name="moblie" placeholder="Enter Mobile Number">
            <app-errors [field]="fatherMobile"></app-errors>
          </div>             
        </div>  
        <div formGroupName="mother" id="mother">
          <h3>Mother's Details :-</h3>
          <div formGroupName="Name">
            <div class="form-group my-3">
              <label for="firstName">First Name:-</label>
              <input formControlName="firstName" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">
              <app-errors [field]="motherFname"></app-errors>
            </div>
            <div class="form-group my-3">
              <label for="middleName">Middle Name:-</label>
              <input formControlName="middleName" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">
              <app-errors [field]="motherMname"></app-errors>
            </div>
            <div class="form-group my-3">
              <label for="lastName">Last Name:-</label>
              <input formControlName="lastName" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
              <app-errors [field]="motherLname"></app-errors>
            </div>
         </div>
          <div class="form-group my-3">
            <label for="email">Email :-</label>
            <input formControlName="email" class="form-control" type="email" id="email" name="email" placeholder="Enter Email">
            <app-errors [field]="motherEmail"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="education">Education Qualification:-</label>
            <input formControlName="education" class="form-control" type="text" id="education" name="education" placeholder="Enter Education">
            <app-errors [field]="motherEducation"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="profession">Profession:-</label>
            <input formControlName="profession" class="form-control" type="text" id="profession" name="profession" placeholder="Enter Profession">
            <app-errors [field]="motherProfession"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="designation">Designation:-</label>
            <input formControlName="desgnation" class="form-control" type="text" id="designation" name="designation" placeholder="Enter Designation">
            <app-errors [field]="motherDesgnation"></app-errors>
          </div>
          <div class="form-group my-3">
            <label for="moblie">Moblie Number:-</label>
            <input formControlName="mobile" class="form-control" type="text" id="moblie" name="moblie" placeholder="Enter Mobile Number">
            <app-errors [field]="motherMobile"></app-errors>
          </div>      
        </div>

        <div formGroupName="EmergencyList">
          <h4>Emergency contect :-</h4>
          <div formArrayName="emeList">
            <div *ngFor="let item of emeList.controls; let i = index" class="form-group my-3">
              <div [formGroupName]="i">
                <div>
                  <label for="designation">Name:-</label>
                  <input formControlName="name" class="form-control" type="text" id="name" name="name" placeholder="Enter Name">                      
                </div>
                <div>
                  <label for="designation">Number:-</label>
                  <input formControlName="number" class="form-control" type="text" id="number" name="number" placeholder="Enter Number">  
                </div>
              </div>
            </div>  
          </div>
          <div>
            <button type="button" class="btn btn-warning" (click)="addEme()">Add person</button>
            <button type="button" class="btn btn-danger" (click)="removeEme()">Remove person</button>

          </div>
        </div>
      </form>
      <input type="submit" value="Submit" (click)="onSubmit()">
  </div>
</div>
{{form.value | json}}
