// Day6/Assignments/Assignment2/Source/react-app/src/ProductList.js
import React, { useState } from 'react'
import Prodcut from './Prodcut';

const ProductList = () => {
    let [prod, setProd] = useState({});
    let [prodList, setList] = useState([]);
        
    const handleProd=(e)=>{
        setProd(p=>({...p,[e.target.name]:e.target.value}))
    }
    console.log(prodList);
    return (
        <div>
            <input type="text" name="title" placeholder='Title' onChange={handleProd}/>
            <input type="number" name="price" placeholder='Price' onChange={handleProd}/>
            <input type="number" name="quantity" placeholder='Quantity' onChange={handleProd}/>
            <button onClick={(e)=>setList([...prodList,prod])}>Submit</button>
            {
                prodList.map((item)=>{
                    return <Prodcut item={item}></Prodcut>
                })
            }
        </div>
  )
}

export default ProductList

// Day6/Assignments/Assignment3/Source/vue-app/src/components/ProductList.vue
<template>

    <input type="text" v-model="prod.name" placeholder="Name">
    <input type="number" v-model="prod.price" placeholder="Price">
    <input type="number" v-model="prod.quantity" placeholder="Quantity">
    <button @click="onSubmit()">Submit</button>
    <div v-for="item in list">
        <Product :item="item"></Product>
    </div>
</template>

<script>

    import Product from './Product.vue';

    export default{
        data(){
            return{
                prod:{
                    name:'',
                    price:null,
                    quantity:null,
                },
                list:[]
            }
        },
        methods:{
            onSubmit(){
                this.list.push({...this.prod})
            }
        },
        components: { Product }
    }

</script>

<style>

</style>
