// Day6/Assignments/Assignment1/Source/angular-app/src/app/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { prodinterface } from '../product/pi';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  prod:prodinterface={
    name:'',
    quantity:'',
    price:''
  }
  list:prodinterface[]=[]
  constructor() { }

  onSubmit(){
    this.list.push({...this.prod})
  }
  ngOnInit(): void {
  }

}

<input type="name" [(ngModel)]="prod.name" placeholder="name"/>
<input type="quantity" [(ngModel)]="prod.quantity" placeholder="quantity"/>
<input type="price" [(ngModel)]="prod.price" placeholder="price"/>
<button (click)="onSubmit()">Submit</button>
<div *ngFor="let prod of list">
    <app-product [prod]="prod"></app-product>
</div>

// Day6/Assignments/Assignment3/Source/vue-app/src/components/ProductList.vue
<template>

    <input type="text" v-model="prod.name" placeholder="Name">
    <input type="number" v-model="prod.price" placeholder="Price">
    <input type="number" v-model="prod.quantity" placeholder="Quantity">
    <button @click="onSubmit()">Submit</button>
    <div v-for="item in list">
        <Product :item="item"></Product>
    </div>
</template>

<script>

    import Product from './Product.vue';

    export default{
        data(){
            return{
                prod:{
                    name:'',
                    price:null,
                    quantity:null,
                },
                list:[]
            }
        },
        methods:{
            onSubmit(){
                this.list.push({...this.prod})
            }
        },
        components: { Product }
    }

</script>

<style>

</style>
