// Day3/Practice/Practice2/Source/react-app/src/component/calc.js
import React, { useState } from 'react'

const Calc = (props) => {
    let [result,setResult] = useState(0)
    const handleCalc = (e)=>{
        e.preventDefault();
        switch (props.opr){
            case '*':
                setResult(parseInt(props.num1)*parseInt(props.num2))
                break;
            case '+':
                setResult(parseInt(props.num1)+parseInt(props.num2))
                break;
            case '-':
                setResult(parseInt(props.num1)-parseInt(props.num2))
                break;
            case '/':
                setResult(parseInt(props.num1)/parseInt(props.num2))
                break;
        }
    }
    return (
        <div>
            <button onClick={handleCalc}>Calculate</button>
            <h1>{result}</h1>
        </div>
    )
}

export default Calc

// Day3/Practice/Practice3/Source/vue-app1/src/components/Calc.vue

<template>
    <h1>{{result}}</h1>
    <button v-on:click='calculate()'>Calculate</button>
</template>


<script>
console.log(this.form);
    export default{
        props:{
            form:{
                num1:Number,
                num2:Number,
                opr:String
            }
        },
        data(){
            return {
                result:''
            }
        },
        methods:{
            calculate(){

                switch(this.form.opr){
                    case '+':
                        this.result = this.form.num1 + this.form.num2
                        break;
                    case '-':
                        this.result = this.form.num1 - this.form.num2
                        break;
                    case '*':
                        this.result = this.form.num1 * this.form.num2
                        break;
                    case '/':
                        this.result = this.form.num1 / this.form.num2
                        break;
                    }       
            }
        }

    }

</script>


<style>
    
</style>
