// Day3/Assignments/Assignment2/Source/react-app/src/components/areaOfRectengle.js
import React, { useState } from 'react'

const AreaOfRectengle = () => {
  let [height,setHeight] = useState(0);
  let [width,setWidth] = useState(0);
  let [res, setRes] = useState(false);

  return (
    <div>
        <h1>Area of rectangle</h1>
        <form  action="">
            <div className="form-group">
                <label >Height</label>
                <input className="form-control" type="number" id="height" name="height" placeholder=" Enter height" onChange={(e)=>setHeight(e.target.value)}/>
            </div>
            <div className="form-group">
                <label >Width</label>
                <input className="form-control" type="number" id="width" name="width" placeholder=" Enter width" onChange={(e)=>setWidth(e.target.value)}/>
            </div>
            <button type="button" onClick={(e)=> setRes(height*width)} className="btn btn-info"  >Find area of ractengle!</button>
        </form>
        <h1>
          {res}
        </h1>
    </div>
  )
}

export default AreaOfRectengle

// Day3/Assignments/Assignment3/Source/vue-app/src/components/areaOfrectengle.vue
<template>
<div>
    <div>
        <h1>Area of rectengle</h1>
        <form  action="">
            <div class="form-group">
                <label for="height">Height</label>
                <input class="form-control" type="number" id="height" name="height" placeholder=" Enter height" v-model="height" >
            </div>
            <div class="form-group">
                <label for="width">Width</label>
                <input class="form-control" type="number" id="width" name="width" placeholder=" Enter width" v-model="width" >
            </div>
            <button type="button" class="btn btn-info" @click="calculate()">Find area of ractengle!</button>
        </form>
    </div>

    <div>
        <h1>{{res}}</h1>
    </div>

    </div>

</template>

<script>
    export default{
        
        data(){
            return {
                height:'',
                width:'',
                res:0
            }
        },
        methods:{
            calculate(){
                this.res=this.height*this.width
            }
        }

    }
</script>

<style>
</style>
