// Day3/Assignments/Assignment2/Source/react-app/src/components/signUp.js
import React, { useState } from 'react'

const SignUp = () => {
    let [form, setForm] = useState({})
    let [disc, setDisc] = useState('')
    console.log(Object.keys(form));
    const handleForm = (e)=>{
        setForm((prev) => ({...prev, [e.target.name]:e.target.value}))
    }
    const handleSignUp = (e)=>{ 
        e.preventDefault()
        if(Object.keys(form).length<6){
            setDisc('Please enter all values!')
        }else{
            setDisc(JSON.stringify(form))
        }
    }
  return (
    <div>
        <h1>Sign up form</h1>
        <form>
            <div className="form-group">
                <label >First Name</label>
                <input type="text" className="form-control" id="first_name" name="first_name" onChange={handleForm} placeholder="Enter First Name."/>
            </div>
            <div className="form-group">
                <label >Last Name</label>
                <input type="text" className="form-control" id="Last-Name" name="Last-Name" onChange={handleForm} placeholder="Enter Last Name."/>
            </div>
            <div className="form-group">
                <label >Email address</label>
                <input type="email" className="form-control" id="email" name="email" onChange={handleForm} placeholder="Enter Email address."/>
            </div>
            <div className="form-group">
                <label >Address</label>
                <input type="text" className="form-control" id="address" name="address" onChange={handleForm} placeholder="Enter address."/>
            </div>  
            <div className="form-group">
                <label >PAN number</label>
                <input type="text" className="form-control" id="pan" name="pan" onChange={handleForm} placeholder="Enter PAN number."/>
            </div>  
            <div className="form-group">
                <label >password</label>
                <input type="password" className="form-control" id="password" name="password" onChange={handleForm} placeholder="Enter password."/>
            </div>
            <button type="button" className="btn btn-info" onClick={handleSignUp}>Sign UP!</button>
        </form>
        <p>{disc}</p>
    </div>
    )
}

export default SignUp

// Day3/Assignments/Assignment3/Source/vue-app/src/components/signUp.vue
<template>
    <div>
        <h1>Sign up form</h1>
        <form>
            <div class="form-group">
                <label for="first_name">First Name</label>
                <input type="text" class="form-control" id="first_name" name="first_name" v-model="formData.FirstName" placeholder="Enter First Name.">
            </div>
            <div class="form-group">
                <label for="Last-Name">Last Name</label>
                <input type="text" class="form-control" id="Last-Name" name="Last-Name" v-model="formData.LastName" placeholder="Enter Last Name.">
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" v-model="formData.Email" placeholder="Enter Email address.">
            </div>
            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" name="address" v-model="formData.Address" placeholder="Enter address.">
            </div>  
            <div class="form-group">
                <label for="pan">PAN number</label>
                <input type="text" class="form-control" id="pan" name="pan" v-model="formData.PAN" placeholder="Enter PAN number.">
            </div>  
            <div class="form-group">
                <label for="password">password</label>
                <input type="password" class="form-control" id="password" name="password" v-model="formData.Passwrod" placeholder="Enter password.">
            </div>
            <button type="button" class="btn btn-info" @click="signUp()">Sign UP!</button>
        </form>
        <div>
            <p>{{discripton}}</p>
        </div>
    </div>
    </template>

<script>
        export default{
            data(){
                return{
                    formData:{
                        FirstName:'',
                        LastName:'',
                        Email:'',
                        Address:'',
                        PAN:'',
                        Passwrod:''
                    },
                    discripton:''
                }
            },
            methods:{
                signUp(){
                    this.discripton=`Name:${this.formData.FirstName} \n Address: ${this.formData.Address} \n PAN : ${this.formData.PAN}`
                }
            }   
        }
</script>
<style>
</style>
