// Day5/Practice/Practice2/Source/react-app/src/App.js
import logo from './logo.svg';
import './App.css';
import { useState } from 'react';

function App() {
  let [num1,setNum1] = useState(0)
  let [num2,setNum2] = useState(0)
  
  return (
    <div className="App">
        <input type='number' name='num1' onChange={(e)=>setNum1(e.target.value)}/>
        <input type='number' name='num2' onChange={(e)=>setNum2(e.target.value)}/>
        {num1==num2 && num1!=0 && num2!=0 && <h1>Both numbers are same</h1>}
        {num1<num2 ? <h1>{num2} is Greater</h1> : <h1>{num1} is Greater</h1>}

    </div>

);
}

export default App;

// Day4/Practice/Practice1/Source/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  num1:number=0
  num2:number=0
  title = 'angular-app';

  get equal(){
    if(this.num1==this.num2) {
      return true
    }else{
      return false
    } 
  }
  get greater(){
    if(this.num1>this.num2) {
      return true
    }else{
      return false
    } 
  }
  
}

<div>
  <h1>Find greater of two numbers.</h1>
  <input type="number" [(ngModel)]="num1" placeholder="ccc">
  <input type="number" [(ngModel)]="num2" placeholder="Number 2">
  <div *ngIf="num1> num2"> <h1> Number 1 one is greater than Number 2 </h1></div>
  <div *ngIf="num1<num2"> <h1> Number 2 two is greater than Number 1 </h1></div>
  <div *ngIf="num1==num2"> <h1> Both number are same </h1></div>
</div>
