// Day7/Assignments/Assignment 3/Source/vue-app/src/components/postList.vue
<template>
    <div class="card shadow-lg" style="width: 18rem;">
    <img class="card-img-top w-75 mx-auto rounded shadow mt-3"  v-bind:src="post.img" alt="Card image cap">
    <div class="card-body">
      <h3 class="card-title">{{post.name}}</h3>
      <p class="card-text">{{post.disc}}</p>
      <div class="d-flex justify-content-end me-4" @click="addLike()">
        <em v-bind:class="post.likeClass"></em>
      </div>
    </div>
    </div>
</template>

<script>
    export default{
        data(){
            return {
                likedPosts:{}
            }
        },
        props:{
            post:Object
        },
        methods:{
            addLike(){
                this.$emit('likedPosts',this.post)
                this.post.likeClass = this.post.likeClass=="fa-regular fa-heart fs-2" 
                ? "fa-solid fa-heart fs-2 text-danger" 
                : "fa-regular fa-heart fs-2"
            }
        }
    }
</script>

<style>

</style>

// Day7/Assignments/Assignment1/Source/angular-app/src/app/post-list/post-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { postInterface } from './postInterface';

@Component({
  selector: 'app-post-list',
  templateUrl: './post-list.component.html',
  styleUrls: ['./post-list.component.css']
})
export class PostListComponent  {
  @Output() likedPosts= new EventEmitter<postInterface>()
  @Input() post!:postInterface


   addLike(){
     this.likedPosts.emit(this.post)
      this.post.likeClass = this.post.likeClass=="fa-regular fa-heart fs-2" 
      ? "fa-solid fa-heart fs-2 text-danger" 
      : "fa-regular fa-heart fs-2"
    }

}

  <div class="card shadow-lg" style="width: 18rem;">
    <img class="card-img-top w-75 mx-auto rounded shadow mt-3"  src='{{post.img}}' alt="Card image cap">
    <div class="card-body">
      <h3 class="card-title">{{post.name}}</h3>
      <p class="card-text">{{post.disc}}</p>
      <div class="d-flex justify-content-end me-4" (click)="addLike()">
        <em class="{{post.likeClass}}"></em>
      </div>
    </div>
    </div>
