// Day3/Practice/Practice2/Source/react-app/src/component/calc.js
import React, { useState } from 'react'

const Calc = (props) => {
    let [result,setResult] = useState(0)
    const handleCalc = (e)=>{
        e.preventDefault();
        switch (props.opr){
            case '*':
                setResult(parseInt(props.num1)*parseInt(props.num2))
                break;
            case '+':
                setResult(parseInt(props.num1)+parseInt(props.num2))
                break;
            case '-':
                setResult(parseInt(props.num1)-parseInt(props.num2))
                break;
            case '/':
                setResult(parseInt(props.num1)/parseInt(props.num2))
                break;
        }
    }
    return (
        <div>
            <button onClick={handleCalc}>Calculate</button>
            <h1>{result}</h1>
        </div>
    )
}

export default Calc

// Day3/Practice/Practice1/Source/angular-app/src/app/calc/calc.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-calc',
  templateUrl: './calc.component.html',
  styleUrls: ['./calc.component.css']
})
export class CalcComponent implements OnInit {
  @Input() num1: any;
  @Input() num2: any;
  @Input() opr!: string;
  result:number=0
  constructor() {

   }

  ngOnInit(): void {
  } 


  caculate(){

    switch (this.opr){
      case '+':
        this.result= parseInt(this.num1) + parseInt(this.num2) 
        break;
      case '-':
        this.result= parseInt(this.num1) - parseInt(this.num2) 
        break;
      case '*':
        this.result= parseInt(this.num1) * parseInt(this.num2) 
        break;
      case '/':
        this.result= parseInt(this.num1) / parseInt(this.num2) 
        break;
      }
  }


}

<button (click)="caculate()">Calculate</button>
<h1>{{result}}</h1>
