// Day9/Assignments/Assignment1/Source/vue-app/src/App.vue
<script>
  import { useVuelidate } from "@vuelidate/core";
  import { required, helpers, minLength } from "@vuelidate/validators";
  import Errors from "./components/Errors.vue";

    export default{
    data() {
        return {
            v$: useVuelidate(),
            stdList:[],
            form: {
                student: {
                    fname: "",
                    mname: "",
                    lname: "",
                    dob: "",
                    birthPlace: "",
                    firstLang: "",
                    city: "",
                    state: "",
                    pin: ""
                },
                father: {
                    fname: "",
                    mname: "",
                    lname: "",
                    email: "",
                    education: "",
                    profession: "",
                    designation: "",
                    mobile: ""
                },
                mother: {
                    fname: "",
                    mname: "",
                    lname: "",
                    email: "",
                    education: "",
                    profession: "",
                    designation: "",
                    mobile: ""
                }
            }
        };
    },
    validations() {
        return {
            form: {
                student: {
                    fname: { required: helpers.withMessage('First name is required!', required) },
                    mname: { required: helpers.withMessage('Middle name is required!', required) },
                    lname: { required: helpers.withMessage('Last name is required!', required) },
                    dob: { required: helpers.withMessage('Date of Birth is required!', required) }
                },
                father: {
                    fname: { required: helpers.withMessage('First name is required!', required) },
                    mname: { required: helpers.withMessage('Middle name is required!', required) },
                    lname: { required: helpers.withMessage('Last name is required!', required) },
                    mobile: { required: helpers.withMessage('Mobile Number is required!', required) }
                },
                mother: {
                    fname: { required: helpers.withMessage('First name is required!', required) },
                    mname: { required: helpers.withMessage('Middle name is required!', required) },
                    lname: { required: helpers.withMessage('Last name is required!', required) },
                    mobile: { required: helpers.withMessage('Mobile is required!', required) }
                }
            }
        };
    },
    components: { Errors },
    methods:{
      submit(e){
        e.preventDefault()
        if(this.v$.$validate()) this.stdList.push(this.form)
        return;
      }
    }
}
</script>

<template>
  <div>
  <div class="container">
    <form  class="d-flex justify-content-between" @submit="submit">
        <div  id="student">
          <h3>Student Details :-</h3>
            <div>
                <div class="form-group my-3">
                  <label for="firstName">First Name:-</label>
                  <input formControlName="firstName" v-model="form.student.fname" @blur="v$.form.student.fname.$touch" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname"> 
                  <Errors :errors="v$.form.student.fname.$errors"></Errors>
                </div>
                <div class="form-group my-3">
                  <label for="middleName">Middle Name:-</label>
                  <input formControlName="middleName" v-model="form.student.mname" @blur="v$.form.student.mname.$touch" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">
                  <Errors :errors="v$.form.student.mname.$errors"></Errors>
                </div>
                
                <div class="form-group my-3">
                  <label for="lastName">Last Name:-</label>
                  <input formControlName="lastName" v-model="form.student.lname" @blur="v$.form.student.lname.$touch" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
                  <Errors :errors="v$.form.student.lname.$errors"></Errors>
                </div>                

              </div>

            <div>
              <div class="form-group my-3">
                <label for="dob">DOB:-</label>
                <input formControlName="dob" v-model="form.student.dob" @blur="v$.form.student.dob.$touch" class="form-control" type="date" id="dob" name="dob">                
                <Errors :errors="v$.form.student.dob.$errors"></Errors>
              </div>

              <div class="form-group my-3">
                <label for="birthPlace">Birth Place:-</label>
                <input formControlName="birthPlace" v-model="form.student.birthPlace" class="form-control" type="text" id="birthPlace" name="birthPlace" placeholder="Enter Birth Place">  
              </div>

              <div class="form-group my-3">
                <label for="firstLang">First Language:-</label>
                <input formControlName="firstLang" v-model="form.student.firstLang" class="form-control" type="text" id="firstLang" name="firstLang" placeholder="Enter First Language">
              </div>
            </div>

            <div >
              <div class="form-group my-3">
                <label for="city">City:-</label>
                <input formControlName="city" v-model="form.student.city" class="form-control" type="text" id="city" name="city" placeholder="Enter Your City">  
              </div>

              <div class="form-group my-3">
                <label for="State">State:-</label>
                <input formControlName="state" v-model="form.student.state" class="form-control" type="text" id="State" name="State" placeholder="Enter Your State">
              </div>              

              <div class="form-group my-3">
                <label for="pin">Enter Pin Code:-</label>
                <input formControlName="pinCode" v-model="form.student.pin" class="form-control" type="text" id="pin" name="pin" placeholder="Pincode">
              </div>

            </div>
        </div>
        <div id="father" >
          <h3>Father's Details :-</h3>
          <div >
              <div class="form-group my-3">
                <label for="firstName">First Name:-</label>
                <input formControlName="firstName" v-model="form.father.fname" @blur="v$.form.father.fname.$touch" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">
                <Errors :errors="v$.form.father.fname.$errors"></Errors>
              </div>
              <div class="form-group my-3">
                <label for="middleName">Middle Name:-</label>
                <input formControlName="middleName" v-model="form.father.mname" @blur="v$.form.father.mname.$touch" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">  
                <Errors :errors="v$.form.father.mname.$errors"></Errors>
              </div>
              <div class="form-group my-3">
                <label for="lastName">Last Name:-</label>
                <input formControlName="lastName" v-model="form.father.lname" @blur="v$.form.father.lname.$touch" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
                <Errors :errors="v$.form.father.lname.$errors"></Errors>
              </div>
          </div>

          <div class="form-group my-3">
            <label for="email">Email :-</label>
            <input formControlName="email" v-model="form.father.email" class="form-control" type="email" id="email" name="email" placeholder="Enter Email">            
          </div>

          <div class="form-group my-3">
            <label for="education">Education Qualification:-</label>
            <input formControlName="education" v-model="form.father.education" class="form-control" type="text" id="education" name="education" placeholder="Enter Education">
          </div>
          
          <div class="form-group my-3">
            <label for="profession">Profession:-</label>
            <input formControlName="profession" v-model="form.father.profession" class="form-control" type="text" id="profession" name="profession" placeholder="Enter Profession">  
          </div>

          <div class="form-group my-3">
            <label for="designation">Designation:-</label>
            <input formControlName="desgnation" v-model="form.father.designation" class="form-control" type="text" id="designation" name="designation" placeholder="Enter Designation">
          </div>
          
          <div class="form-group my-3">
            <label for="moblie">Moblie Number:-</label>
            <input formControlName="mobile" v-model="form.father.mobile" @blur="v$.form.father.mobile.$touch" class="form-control" type="text" id="moblie" name="moblie" placeholder="Enter Mobile Number">
            <Errors :errors="v$.form.father.mobile.$errors"></Errors>
          </div>

        </div>  
        <div  id="mother">
          <h3>Mother's Details :-</h3>
          <div>
            <div class="form-group my-3">
              <label for="firstName">First Name:-</label>
              <input formControlName="firstName" v-model="form.mother.fname" @blur="v$.form.mother.fname.$touch" class="form-control" type="text" id="firstName" name="firstName" placeholder="Enter Firstname">  
              <Errors :errors="v$.form.mother.fname.$errors"></Errors>
            </div>

            <div class="form-group my-3">
              <label for="middleName">Middle Name:-</label>
              <input formControlName="middleName" v-model="form.mother.mname" @blur="v$.form.mother.mname.$touch" class="form-control" type="text" id="middleName" name="middleName" placeholder="Enter Middlename">  
              <Errors :errors="v$.form.mother.mname.$errors"></Errors>
            </div>

            <div class="form-group my-3">
              <label for="lastName">Last Name:-</label>
              <input formControlName="lastName" v-model="form.mother.lname" @blur="v$.form.mother.lname.$touch" class="form-control" type="text" id="lastName" name="lastName" placeholder="Enter Lastname">
              <Errors :errors="v$.form.mother.lname.$errors"></Errors>
            </div>
         </div>

          <div class="form-group my-3">
            <label for="email">Email :-</label>
            <input formControlName="email" v-model="form.mother.email" class="form-control" type="email" id="email" name="email" placeholder="Enter Email">
          </div>

          <div class="form-group my-3">
            <label for="education">Education Qualification:-</label>
            <input formControlName="education" v-model="form.mother.education" class="form-control" type="text" id="education" name="education" placeholder="Enter Education">
          </div>

          <div class="form-group my-3">
            <label for="profession">Profession:-</label>
            <input formControlName="profession" v-model="form.mother.profession" class="form-control" type="text" id="profession" name="profession" placeholder="Enter Profession">
          </div>

          <div class="form-group my-3">
            <label for="designation">Designation:-</label>
            <input formControlName="desgnation" v-model="form.mother.designation" class="form-control" type="text" id="designation" name="designation" placeholder="Enter Designation">
          </div>

          <div class="form-group my-3">
            <label for="moblie">Moblie Number:-</label>
            <input formControlName="mobile" v-model="form.mother.mobile" @blur="v$.form.mother.mobile.$touch" class="form-control" type="text" id="moblie" name="moblie" placeholder="Enter Mobile Number">
            <Errors :errors="v$.form.mother.mobile.$errors"></Errors>
          </div>        
        </div>

        <div>
          <h4>Emergency contect :-</h4>
          <div formArrayName="emeList">
            <div  class="form-group my-3">
              <div >
                <div>
                  <label for="designation">Name:-</label>
                  <input formControlName="name" class="form-control" type="text" id="name" name="name" placeholder="Enter Name">                      
                </div>
                <div>
                  <label for="designation">Number:-</label>
                  <input formControlName="number" class="form-control" type="text" id="number" name="number" placeholder="Enter Number">  
                </div>
              </div>
            </div>  
          </div>
          <div>
            <button type="button" >Add person</button>
            <button type="button">Remove person</button>

          </div>
          <button class="btn btn-success" type="submit">Submit</button>
          </div>
      </form>
  </div>
</div>
<!-- {{form.value | json}} -->

{{Object.keys(v$.form.father)}}
</template>

<style>
</style>

// Day10/Practice/Practice1/Source/react-app/src/App.js

import { useState } from 'react';
import { useFieldArray, useForm } from 'react-hook-form';
import './App.css';
import InputsComponents from './components/InputsComponents';
function App() {
  let {register, control,handleSubmit,formState:{errors}} = useForm({ mode: "onBlur"})
  let {fields,append,remove} = useFieldArray({control,name:'eme'})
  let [studentList, setStudentList] = useState();
  const submit = (data)=>{    
    setStudentList([...studentList,data])
  }
  
  const addEme=()=>{
    append({Ename:'',Enumber:''})
  }

  return (
    <div className="App">
    <div className="container">
    <form onSubmit={handleSubmit(submit)}>
      <div className="d-flex justify-content-between">
        <div id="student">
          <h3>Student Details :-</h3>
            <div>
              <InputsComponents inputType='text' label={'First Name'} fieldName='SfirstName' register={register} errors={errors} placeHolder="Enter First Name"> </InputsComponents>
              {errors.SfirstName && <span className='text-danger'>This field is required❗</span>}
              <InputsComponents inputType='text' label={'Middle Name'} fieldName='SmiddleName' register={register} errors={errors} placeHolder="Enter Middle Name"> </InputsComponents>
              {errors.SmiddleName && <span className='text-danger'>This field is required❗</span>}
              <InputsComponents inputType='text' label={'Last Name'} fieldName='SlastName' register={register} errors={errors} placeHolder="Enter Last Name"> </InputsComponents>
              {errors.SlastName && <span className='text-danger'>{errors.SlastName?.message}</span>}      
            </div>
            <div>
            <InputsComponents inputType='date' label={'Date Of Birth'} fieldName='dob' register={register} errors={errors} placeHolder="Birth Date"> </InputsComponents>
            {errors.dob && <span className='text-danger'>This field is required❗</span>}

              <div className="form-group my-3">
                <label htmlFor="birthPlace">Birth Place:-</label>
                <input className="form-control" {...register('birthPlace')} type="text" id="birthPlace" name="birthPlace"  placeholder="Enter Birth Place"/>  
              </div>

              <div className="form-group my-3">
                <label htmlFor="firstLang">First Language:-</label>
                <input  className="form-control" {...register('firstLang')} type="text" id="firstLang" name="firstLang"  placeholder="Enter First Language"/>
              </div>
            </div>

            <div >
              <div className="form-group my-3">
                <label htmlFor="city">City:-</label>
                <input  className="form-control" {...register('city')} type="text" id="city" name="city"  placeholder="Enter Your City"/>  
              </div>

              <div className="form-group my-3">
                <label htmlFor="State">State:-</label>
                <input  className="form-control" {...register('State')} type="text" id="State" name="State"  placeholder="Enter Your State"/>
              </div>              

              <div className="form-group my-3">
                <label htmlFor="pin">Enter Pin Code:-</label>
                <input  className="form-control" {...register('pin')} type="text" id="pin" name="pin"  placeholder="Pincode"/>
              </div>

            </div>
        </div>
        <div id="father" >
          <h3>Father's Details :-</h3>
          <div >
              <InputsComponents inputType='text' label={'First Name'} fieldName='FfirstName' register={register} errors={errors} placeHolder="Enter First Name"> </InputsComponents>
              {errors.FfirstName && <span className='text-danger'>This field is required❗</span>}
              <InputsComponents inputType='text' label={'Middle Name'} fieldName='FmiddleName' register={register} errors={errors} placeHolder="Enter Middle Name"> </InputsComponents>
              {errors.FmiddleName && <span className='text-danger'>This field is required❗</span>}
              <InputsComponents inputType='text' label={'Last Name'} fieldName='FlastName' register={register} errors={errors} placeHolder="Enter Last Name"> </InputsComponents>
              {errors.FlastName && <span className='text-danger'>This field is required❗</span>} 
          </div>

          <div className="form-group my-3">
            <label htmlFor="email">Email :-</label>
            <input  className="form-control" {...register('Femail')} type="email" id="Femail" name="Femail"  placeholder="Enter Email"/>            
          </div>

          <div className="form-group my-3">
            <label htmlFor="education">Education Qualification:-</label>
            <input  className="form-control" {...register('Feducation')} type="text" id="Feducation" name="Feducation"  placeholder="Enter Education"/>
          </div>
          
          <div className="form-group my-3">
            <label htmlFor="profession">Profession:-</label>
            <input  className="form-control" {...register('Fprofession')} type="text" id="Fprofession" name="Fprofession"  placeholder="Enter Profession"/>  
          </div>

          <div className="form-group my-3">
            <label htmlFor="designation">Designation:-</label>
            <input  className="form-control" {...register('Fdesignation')} type="text" id="Fdesignation" name="Fdesignation"  placeholder="Enter Designation"/>
          </div>
          
          <div className="form-group my-3">
            <label htmlFor="moblie">Moblie Number:-</label>
            <input  className="form-control" {...register('Fmoblie')} type="text" id="Fmoblie" name="Fmoblie"  placeholder="Enter Mobile Number"/>
          </div>
        </div>  
        <div  id="mother">
          <h3>Mother's Details :-</h3>
          <div>
            <InputsComponents inputType='text' label={'First Name'} fieldName='MfirstName' register={register} errors={errors} placeHolder="Enter First Name"> </InputsComponents>
              {errors.MfirstName && <span className='text-danger'>This field is required❗</span>}
              <InputsComponents inputType='text' label={'Middle Name'} fieldName='MmiddleName' register={register} errors={errors} placeHolder="Enter Middle Name"> </InputsComponents>
              {errors.MmiddleName && <span className='text-danger'>This field is required❗</span>}
              <InputsComponents inputType='text' label={'Last Name'} fieldName='MlastName' register={register} errors={errors} placeHolder="Enter Last Name"> </InputsComponents>
              {errors.MlastName && <span className='text-danger'>This field is required❗</span>} 
         </div>

          <div className="form-group my-3">
            <label htmlFor="email">Email :-</label>
            <input className="form-control" {...register('Memail')} type="email" id="Memail" name="Memail"  placeholder="Enter Email"/>
          </div>

          <div className="form-group my-3">
            <label htmlFor="education">Education Qualification:-</label>
            <input className="form-control" {...register('Meducation')} type="text" id="Meducation" name="Meducation"  placeholder="Enter Education"/>
          </div>

          <div className="form-group my-3">
            <label htmlFor="profession">Profession:-</label>
            <input   className="form-control" {...register('Mprofession')} type="text" id="Mprofession" name="Mprofession"  placeholder="Enter Profession"/>
          </div>

          <div className="form-group my-3">
            <label htmlFor="designation">Designation:-</label>
            <input   className="form-control" {...register('Mdesignation')} type="text" id="Mdesignation" name="Mdesignation"  placeholder="Enter Designation"/>
          </div>

          <div className="form-group my-3">
            <label htmlFor="moblie">Moblie Number:-</label>
            <input className="form-control" {...register('Mmobile')} type="text" id="Mmoblie" name="Mmoblie"  placeholder="Enter Mobile Number"/>
          </div>   
        </div>

        <div>
          <h4>Emergency contect :-</h4>
          <div >
            <div  className="form-group my-3">
              {fields.map((item,index)=>{
                return (<div>
                          <div>
                            <label htmlFor="designation">Name:-</label>
                            <input  className="form-control" {...register(`eme.${index}.Ename`)} type="text" id="Ename" name="Ename" placeholder="Enter Name"/>                      
                          </div>
                          <div>
                            <label htmlFor="designation">Number:-</label>
                            <input  className="form-control" {...register(`eme.${index}.Enumber`)} type="text" id="Enumber" name="Enumber" placeholder="Enter Number"/>  
                          </div>
                        </div>)
              })}
            </div>  
          </div>
          <div className='d-flex justify-content-between'>
            <button type="button"  onClick={addEme} className='btn btn-warning'>Add</button>
            <button type="button" onClick={(e)=>remove(fields.length-1)} className='btn btn-danger'>Remove</button>
          </div>

        </div>
      </div>
      <div className='text-center'>
          <button className="btn btn-success" type="submit">Submit</button>     
      </div>
      </form>
  </div>
    </div>
  );
}

export default App;
