// Day3/Assignments/Assignment3/Source/vue-app/src/components/login.vue
<template>
<div>
    <h1>Login Form</h1>
    <form>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" v-model="username" placeholder="Enter username.">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" v-model="password" placeholder="Enter Password.">
        </div>
        <button type="button" class="btn btn-info" @click="login()">Login!</button>
    </form>
    <div>
        <p>{{errMsg}}</p>
    </div>
</div>
</template>
<script>
export default{
    data(){
        return{
            username:'',
            password:'',
            errMsg:''
        }
    },
    methods:{
        login(){
            if (this.username.length>0 && this.password.length>=0){
                if(this.username=="admin" && this.password=='admin'){
                    this.errMsg=`${this.username} is logged in`
                }
                else{
                    this.errMsg=`You are not registerd`                    
                }
            }
            else{
                this.errMsg=`Enter values`                                    
            }
        }
    }
}
</script>
<style>
</style>

// Day3/Assignments/Assignment2/Source/react-app/src/components/login.js
import React, { useState } from 'react'

const Login = () => {
    let [username,setUsername] = useState('');
    let [password, setPassword] = useState('');
    let [errMsg, setErrMsg] = useState('')

    const handleLogin = (e)=>{
        e.preventDefault();

        if(username!=='' && password!==''){
            if(username==='admin' && password==='admin'){
                setErrMsg(`${username} is logged in`)
            }
            else{
                
                setErrMsg(`${username} is not registerd`)
            }
        }
        else{
            setErrMsg(`Enter values!`)
        }
    }
    return (
        <div>
            <h1>Login Form</h1>
            <form>
                <div className="form-group">
                    <label >Username</label>
                    <input type="text" className="form-control" id="username" name="username" onChange={(e)=>setUsername(e.target.value)} placeholder="Enter username."/>
                </div>
                <div className="form-group">
                    <label >Password</label>
                    <input type="password" className="form-control" id="password" name="password" onChange={(e)=>setPassword(e.target.value)} placeholder="Enter Password."/>
                </div>
                <button type="button" className="btn btn-info" onClick={handleLogin}>Login!</button>
            </form>
            <p>
            {errMsg }
            </p>
        </div>
    )
}

export default Login
